#!/usr/bin/with-contenv bash
run_cmd() {
    set +e

    cmd=$@
    if [ "${DEBUG}" == "TRUE" ]
    then
        echo "Executing [$cmd]"
    fi
    eval $cmd
    ret_code=$?

    if [ "$ret_code" == "0" ]
    then
        echo "$@ executed successfully"
    else
        echo "$@ failed with exit code [$ret_code]"
    fi
}

echo "Starting mysql service"
run_cmd "sudo -u ${USER} /usr/bin/mysqld_safe --skip-syslog"
#--binlog-format=MIXED
echo "Finishing mysql service"
